### ISSUE TITLE
UI: Filter by column values

### ISSUE THREAD

**Issue by alexcrichton** [barosl/homu#10]
aka: "all PRs assigned to foo" or "all PRs that are failed" or "all mergeable PRs", etc.

This may also be able to be accomplished by being able to sort each column

**Comment by Gankro** [comment]
I'm interested in doing this, and I think it's more useful than sorting, honestly. With sorting you have to be able to find where the results you're interested in ended up. 

Although I suppose this might be handled "at the same time" by a nice table library.

**Comment by Gankro** [comment]
I'm trying to work out the desired UX here. It's possible to have both global and column-specific filters. In theory by-column is more "useful" but it's not like we're trying to build a SQL database here, we just want people to be able to quickly reduce the dataset to something manageable, right? If that's the case, only providing global seems like a good choice.

Some quick tests of global search using DataTables:

Searching for failed PRs:
![screenshot from 2015-01-19 01 39 57](https://cloud.githubusercontent.com/assets/1136864/5796808/755ebaa6-9f7c-11e4-8369-64d8bc5db848.png)


Searching for niko-related PRs:
![screenshot from 2015-01-19 01 40 06](https://cloud.githubusercontent.com/assets/1136864/5796809/7af261c0-9f7c-11e4-9252-38495b732d7a.png)

The results are imperfect, but "good enough" for humans to deal with, I think. Thoughts?

**Comment by Gankro** [comment]
DataTables also includes sorting so you can refine any of these results by just clicking on the column's header, if desired.

**Comment by alexcrichton** [comment]
That all looks fantastic to me!
