### ISSUE TITLE
homu.io: Unable to add a webhook: MissingFieldError("id")

### ISSUE THREAD

**Issue by MichaelHirn** [barosl/homu#103]
I get this error, when I try to register my repo at homu.io. Yesterday, I set up a repo successfully for another organization, but today it won't work anymore. I am Admin/Owner at both organizations. Any clues on what that error means?

**Comment by MichaelHirn** [comment]
The probles was, that homu was registered only with the first organization, which then somehow resulted in that error. I removed the authorization from the first organization and did the Register again - worked.

**Comment by barosl** [comment]
Hi! Thanks for reporting, and I'm investigating this issue now, as I think the error message should be more friendly. It seems that one of the reasons that show such an error message ("Unable to add a webhook") is that the webhook was somehow already registered, and adding the same webhook twice is refused by GitHub. So, I want to be confirmed: when you removed the authorization from the organization, did you also unregister the webhook manually?

**Comment by MichaelHirn** [comment]
Hi barosl. Frankly speaking, I do not know anymore. I tried all different kind of changes - including removing/changing the webhook. So there is a good change, that there was no registered webhook anymore, when I got it to run, but I can't say for sure.

**Comment by barosl** [comment]
I see. Probably removing the webhook did the trick. I hope this bug doesn't happen anymore!

Anyways, sorry for the inconvenience, and again thanks for reporting this issue!

**Comment by badboy** [comment]
I'm facing the same issue when trying to register any repo under the @semantic-rs organization.
I'm getting a `You don't have permission on this repository` when trying to add.
If I add the homu user manually as a contributor (with write rights), I get the `MissingFieldError`.
