### ISSUE TITLE
Include PR desc in merge commit

### ISSUE THREAD

**Issue by ligthyear** [barosl/homu#116]
First of, thanks for the great work! We are using homu at [beavy](https://github.com/beavyHQ/beavy) and it works just great. It is especially great as our setup encourages people to have PRs on their own forks, but when reviewing happens in bulk we often weren't able to merge, because people had to update their branches. Homu fixes that and reminds people when there is an merge conflict to fix when there is. Our process now requires that things can only be merged once travis _and homu_ confirmed them. That is awesome, thanks for that work!

This issue is more an improvement rather than a bug: We use the PR to not only discuss the feature but also include a longer description of what is happening and _why a change was made_ in the description. Unfortunately this information is lost at the moment homu merges the PR. **It'd be awesome if we could inform homu that it should include the issue desc in the body of the merge-commit**, so you have a big explanatory changelog when going through the master history.

Keep up the great work!

**Comment by sigmavirus24** [comment]
@ligthyear do you mean the original description or the entire conversation?

**Comment by ligthyear** [comment]
@sigmavirus24 for what we need: the original description.

We keep that up to date (and whoever reviews, can usually also update that right before) throughout the conversation. I think adding the entire conversation makes it more confusing than helpful.

**Comment by ligthyear** [comment]
Wait a second. Am I seeing this already? How did I miss this before? Sorry for bothering you, it appears you already have that feature in there. Closing the issue.
