### ISSUE TITLE
Can't register despite having permissions

### ISSUE THREAD

**Issue by indirect** [barosl/homu#120]
While trying to register `rubygems/rubygems` at homu.io, I get the error "You don't have permission on this repository"... but I definitely have permission. I can edit settings, teams, collaborators, and webhooks on that repository.

**Comment by sigmavirus24** [comment]
@indirect do you have the "Third-party application policy" set to restricted? I'm not certain if this might be causing it, but it might be worth investigating.

**Comment by barosl** [comment]
Do you still have this problem?

**Comment by indirect** [comment]
Yes, I still have this problem (sorry, I somehow missed this comment!). I just opened a new issue about it at #132, having completely forgotten that I opened this earlier.

**Comment by indirect** [comment]
Closing this in favor of #132, which has more details and a (possibly dangerous to organization security) workaround.
