### ISSUE TITLE
Homu queue is down and doesn't process request

### ISSUE THREAD

**Issue by Ryman** [barosl/homu#124]
Examples [here](https://github.com/gtk-rs/gir/pull/189#issuecomment-171298520) and [here](https://github.com/nickel-org/nickel.rs/pull/299#issuecomment-171221041)

**Comment by Ryman** [comment]
Curiously, manually retriggering a travis build causes homu to kick in and merge via test-exemption!

**Comment by barosl** [comment]
There was a brief network shortage that caused Homu to stop working. Strangely, `homu.io` which is made of `nickel.rs` survived, but the Python daemon itself had been blocked for several hours. I guess it was waiting for some lost packets, but I'm not sure.

**Comment by Ryman** [comment]
OK, no worries, will close if it's just intermittent :)

Thanks for the update!
