### ISSUE TITLE
Two PRs being tested at once

### ISSUE THREAD

**Issue by alexcrichton** [barosl/homu#21]
The cargo queue currently has two PRs being tested at once:

![https://i.imgur.com/VCu9tDQ.png](https://i.imgur.com/VCu9tDQ.png)

![https://i.imgur.com/A8GojT7.png](https://i.imgur.com/A8GojT7.png)

**Comment by alexcrichton** [comment]
Note that I approved 1126 first and then approved 1107

**Comment by barosl** [comment]
Gosh, I can't believe I made such a mistake. Now it should be fixed. Thanks for reporting the bug!
