### ISSUE TITLE
PRs closed then reopened are forgotten

### ISSUE THREAD

**Issue by alexcrichton** [barosl/homu#22]
https://github.com/rust-lang/cargo/pull/1120 was close but then reopened, and it no longer appeared on the status page

**Comment by barosl** [comment]
Did you manually restarted Homu? It seems that 1120 is shown in the status page.

**Comment by alexcrichton** [comment]
Yeah (was gonna approve it but found something else)

**Comment by barosl** [comment]
Uhm, I'm not sure how to reproduce it. In my local test, it does recognize the reopened PRs. In the source code the `reopened` event is handled explicitly... Any exceptions occurred?

**Comment by alexcrichton** [comment]
Hm I don't think so, maybe it was for some other reason then. I'll reopen if I see it happen again.
