### ISSUE TITLE
Notifications about stale PRs

### ISSUE THREAD

**Issue by alexcrichton** [barosl/homu#24]
It would be awesome if homu could post a comment on the *author's* repository indicating when a PR has become stale (will no long merge cleanly). That way it wouldn't spam rust-lang/rust but it would be a good reminder to go rebase a PR.

**Comment by barosl** [comment]
I was also planning to propose this. One of the concerns was how often we should notify the author. One option is to inform only once, which is good enough I think. Another option is to inform periodically, for the author who forgot that his/her PR was unmergeable. However to adopt the latter approach, we should save another bit of state to the local database. So I wanted to know it was worth.

**Comment by alexcrichton** [comment]
For now I think once is enough, we could possibly expand later but better to start off conservative :)

**Comment by sanxiyn** [comment]
Did 80b6914 fix this?

**Comment by barosl** [comment]
Yes, it did. Thanks for the reminder, @sanxiyn!
