### ISSUE TITLE
UI: auto-refresh

### ISSUE THREAD

**Issue by alexcrichton** [barosl/homu#26]
the old bors page had an auto-refresh of every 2m or so, perhaps homu could do the same?

Bors did this via:

```
    <meta http-equiv="refresh" content="120">
```

**Comment by barosl** [comment]
Personally, I didn't like the automatic refresh behavior because I often wanted to see the state at the time when the queue page is opened. However, many people seem to like the behavior, so I'm thinking of adding a checkbox that turns on automatic refresh. Does this make sense?

**Comment by alexcrichton** [comment]
Sounds good to me!
