### ISSUE TITLE
Suggest longer SHAs

### ISSUE THREAD

**Issue by alexcrichton** [barosl/homu#27]
It looks like github [doesn't auto-link](https://github.com/rust-lang/rust/pull/21366#issuecomment-70437491) 4-character SHAs, which while I think that's fine for the comment, when approving it's nice to be able to link to the exact commit that was approved (via github as well).

**Comment by barosl** [comment]
My original intention was to emphasize that short SHAs can be used to `r+` things. But I agree that a link to the exact commit would be nice to see.

Do you think we should promote using short SHAs in other ways? (Like, directly specifying `you can use short SHAs` in the comments?) Or, would just mentioning it in the manual be sufficient?

**Comment by alexcrichton** [comment]
I think short SHAs are definitely fine, I just thought that only 4 characters was a little short.
