### ISSUE TITLE
Create a Python package

### ISSUE THREAD

**Issue by bheesham** [barosl/homu#3]
This would make installation easy (`pip install homu`, `python setup.py install`, etc).
Would also mean that starting homu could be as easy as `homu -c CONF`.

I have some initial work in my package branch of homu: https://github.com/bheesham/homu/tree/package.

I'll submit a pull req once it's complete.

**Comment by barosl** [comment]
This had been done by 32c08b6, except the ability to choose the configuration file. Closing for now.
