### ISSUE TITLE
Button for rolling up all PRs

### ISSUE THREAD

**Issue by alexcrichton** [barosl/homu#32]
I frequently like to roll up the entire queue all at once, even those not tagged with `rollup`. I then test everything locally and likely hit tons of failures, but I tend to fix them in an extra commit.

Could an extra button be added to roll up the entire approved queue instead of just the rollup-marked PRs?

**Comment by Gankro** [comment]
How would this mode handle merge conflicts?

**Comment by barosl** [comment]
@alexcrichton Aside from this very issue, I think implementing a general interface that lets you choose the PRs to be rolled up is useful. Like, each PR has a checkbox next to it, and you let Homu merge all the checked PRs.

@Gankro It can be processed as the same as the current `rollup` behavior. Those that conflict will not be merged, listed in the "failed merges" section.

**Comment by alexcrichton** [comment]
@barosl that sounds great to me!
