### ISSUE TITLE
queue: HTML escape the PR title

### ISSUE THREAD

**Issue by japaric** [barosl/homu#37]
If you take a look at the [queue] right now, you'll see that PR #21392 doesn't show its full title ("impl Iterator for &mut Iterator and Box<Iterator>") because the `<>` characters didn't get escaped.

[queue]: http://buildbot.rust-lang.org/homu/queue/rust

**Comment by barosl** [comment]
Huh? It is so embarrassing! I can't believe I forgot escaping. I'll fix it in a hurry.

**Comment by barosl** [comment]
It turns out that unlike Flask, Jinja2 does not turn on autoescape by default. I should have read the documentation more carefully. :/
