### ISSUE TITLE
Use flask or flacon to serve requests

### ISSUE THREAD

**Issue by FlaPer87** [barosl/homu#42]
`Homu` currently uses the standard library threading and http modules. While this may work fine for some things, they don't have the same results in terms of performance, readability and structure as the frameworks mentioned in the subject do.

Therefore, I think it'd be worth it to spend some time in a small refactor to adopt one of those frameworks. Based on the fact that we're already using jinja2, I believe flask would be more appropriate. Although this is not a strict rule.

**Comment by FlaPer87** [comment]
Also, I may take a stab at this in the next few days

**Comment by barosl** [comment]
I agree that readability and structure are important factors, but I also think performance isn't really important regarding the low traffic nature of these kinds of application. My bigger concern is memory consumption, as Homu is already consuming more memory than my expectation.

I believe that any framework will allow us to structure Homu better. And I also think that REST-ful frameworks like Falcon are overkill, as we're not going to utilize any advanced routing.

So I've tested some microframeworks in regard to memory usage. According to my unscientific tests, Flask consumes ~6M more than `http.server`, whereas Bottle consumes only ~2M more.

So I'm more inclined to use Bottle for our purposes. Also, the development of Bottle seems to be more active than Flask. The last release of Flask was in 2013, for reference. More importantly, I thought it would be fun to try something new!

**Comment by FlaPer87** [comment]
@barosl In the past, Bottle has given me more problem than it's actually helped me fixing. From memory consumption to correct handling of file descriptors. 

I agree a REST-ful framework may be more than what's actually needed here but I don't think that precise point is what we should be looking at. I'd rather give more value to the readability, maintainability and ease for collaboration.

If you look at Flak's repo, it's still receiving patches and AFAIK, it's not going away. We can let the author chime in here. @mitsuhiko comments?

That said, I'm not sure what your memory consumption requirements are but I'd argue there should actually be one. I'm not recommending we should just consume all the memory but I don't think 6M is a problem here. I've no idea why the current version is consuming more memory than you'd expect nor I know how much memory it is consuming. However, this will depend a lot on the code, the server will have little to do in this as the memory consumed by the framework should be relative to the number of connections it's keeping open.

**Comment by barosl** [comment]
Your experience on Bottle makes me discouraged from using it! I'm so sad.

Maybe I'm just a bit obsessive on the memory consumption, considering 6M is never a big deal on modern hardware. I just wanted Homu to consume memory similar to typical command line tools, but as it's written in Python, it probably can never happen.
