### ISSUE TITLE
Incorrect number error could list the part that was attempted to be used as the commit

### ISSUE THREAD

**Issue by huonw** [barosl/homu#54]
e.g. 

- `@bors r+`: "no commit SHA found. please try again with ..."
- `@bors r+ 1234`: "found '1234' which is not a recognised commit SHA. please try again with ..." (assuming commit 1234 doesn't exist)
- `@bors r+ foobarbaz 1234`: "found 'foobarbaz' which is not a recognised commit SHA. please try again with ..." (the scenario being the user put things in the wrong order)

**Comment by Gankro** [comment]
:+1: I suck and I need homu to teach me how to not suck.
