### ISSUE TITLE
Multi-repo dashboards

### ISSUE THREAD

**Issue by Ms2ger** [barosl/homu#57]
This would be useful for Servo, because we have a boatload of small repos that nobody really watches.

**Comment by Gankro** [comment]
Sounds pretty doable as just:

http://buildbot.rust-lang.org/homu/queue/rust+cargo

and the backend just pools the results.

**Comment by Gankro** [comment]
Looking at implementing this. Would you prefer that all results be interspersed completely as if they came from one repo, or should the default sort separate them somehow?

**Comment by Ms2ger** [comment]
I don't care much either way.
