### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by astrieanna** [barosl/homu#68]
I couldn't find a License file in the repo, or a reference to a license in the README. What open-source license is homu using?

**Comment by Gankro** [comment]
Oh, I didn't even realize that a license hadn't been specified. @barosl I'm cool with licensing my contributions under any BSD/MIT/Apache-style license. I guess GPL too.

**Comment by barosl** [comment]
I haven't decided it yet, but I guess it would be good to follow the same license as the one the Rust project is using (MIT + Apache). I used to apply GPL years ago, but nowadays MIT seems to be more popular. I also want to hear the opinions from others. Do you have any preferences?

**Comment by astrieanna** [comment]
@barosl  Is that question aimed at me? I don't think my opinion has much weight here, since I haven't made any contributions to this project. I'm very happy with any mainstream non-GPL license, and I guess GPL is alright, too.
