### ISSUE TITLE
OAuth Callback URL

### ISSUE THREAD

**Issue by sonOfRa** [barosl/homu#76]
The README mentions that I need to create a new OAuth Application. What are the correct parameters for the Homepage URL and the Authorization callback URL here?

**Comment by barosl** [comment]
Oh! I forgot to mention that in the documentation. The homepage URL doesn't have to be specified, and the callback URL should be `http://HOST:PORT/rollup`. The latter isn't mandatory, as the URL is only used for the "rollup" functionality, which is primarily targeted for the really huge repositories (e.g. the Rust project). So you may empty those two URL fields.

I'll leave this issue open to add the description to the README.
