### ISSUE TITLE
try builds on Servo flood Buildbot

### ISSUE THREAD

**Issue by Manishearth** [barosl/homu#83]
We tried @bors-servo: try on https://github.com/servo/servo/pull/6244, and buildbot was queued up with around 200 PRs starting around January (all on the try branch).

Our config: https://github.com/servo/saltfs/blob/master/homu/cfg.toml ([buildbot config](https://github.com/servo/saltfs/tree/master/buildbot)

Some example builds: http://build.servo.org/builders/mac2/builds/2106 , http://build.servo.org/builders/mac2/builds/2107 , http://build.servo.org/builders/mac2/builds/2108 , http://build.servo.org/builders/mac2/builds/2109

Did we do something wrong here? Is this a homu bug?

cc @larsbergstrom @edunham

**Comment by alexcrichton** [comment]
This used to happen to us in Rust, and we ended up just setting a higher [`treeStableTimer` option](https://github.com/rust-lang/rust-buildbot/blob/5d057e7744477a7582fefd48ab7648ffa07c80d6/master/master.cfg#L371) when making the schedulers (maybe relevant?)
