### ISSUE TITLE
homu should avoid spurious builds when using Travis CI

### ISSUE THREAD

**Issue by metajack** [barosl/homu#93]
Right now the default homu flow when using travis causes these builds:

1) Original PR commit built by travis (which is actually a merge commit with master)
2) `auto` branch when homu merges for testing
3) `master` branch when the final merge happens

Build 3 is redundant always, since that merge is always a fast forward with homu. You can remove this spurious build by adding `branches: except: - master` to `.travis.yml`, but unfortunately that turns of PR builds altogether.

However, Build 2 is often redundant as well. Travis CI already tests a merge commit, not the branch commit. In the case where master has not advanced past where homu tested it, homu could skip this build altogether and merge immediately. This would make the workflow even faster.

**Comment by stefanpenner** [comment]
> but unfortunately that turns of PR builds altogether.

This may be good actually, if homu takes over all CI runs, it would have sufficient knowledge to skip redundant CI runs.

1. PR is submitted
2. homu kicks off CI run, stores result + reports back
3. if a reviewer then says `@homu r+`, and no additional commits to master, homu can insta merge.

If mainline commits land, and then a reviewer says `@homu r+`, homu clearly needs to re-run.

––––

I suppose passing off to homu entirely could be mitigated if it had the ability to peek into the relevant CI run. (Which it may already be able to do)

**Comment by metajack** [comment]
That could work if homu took over all the scheduling functions of travis.
