### ISSUE TITLE
Homu merges to master rather than the branch a PR is open against

### ISSUE THREAD

**Issue by indirect** [barosl/homu#95]
This may be out of scope for Homu in general, but it seems like Homu tries to merge approved commits to `master`, even if the PR was opened against a different branch that isn't master. Am I doing it wrong? Is it just impossible to use Homu on PRs against non-master branches?

**Comment by barosl** [comment]
Oops, you're right. Homu itself has a configuration option to change the base branch, but http://homu.io/ currently doesn't support such a thing. And also, the configured base branch is applied to all the PRs, regardless of individual branch each PR is targeted for.

I'll tackle this problem soon.

**Comment by barosl** [comment]
Thanks for reporting!

**Comment by indirect** [comment]
Whoa, so fast! Thanks! Any idea when I'll be able to use this change with homu.io?

**Comment by barosl** [comment]
I restarted the server a while ago, so it should have been already applied, I believe.
