### ISSUE TITLE
Frequently exceeding GH API rate limits

### ISSUE THREAD

**Issue by larsbergstrom** [barosl/homu#97]
On Servo, we're seeing homu die every couple of days due to exceeding GH API rate limits. Are there any solutions to this problem that we can do on our side? I see a bunch of stuff about Conditional Requests, etc. here: https://developer.github.com/v3/#conditional-requests, and we could certainly help with some patches.

Otherwise, should we be using account-per-repo or something?

cc @jdm, @metajack, @edunham

**Comment by metajack** [comment]
Even just being able to have homu respect the rate limit would probably help a lot.

**Comment by larsbergstrom** [comment]
@barosl We are hitting this roughly hourly on Servo. halp.

**Comment by larsbergstrom** [comment]
Hahaha! This was us, overusing the account for something else. Na'ermind :-)
